(* AUTOGENERATED FILE - DO NOT EDIT MANUALLY *)


type __ = Obj.t
let __ = let rec f _ = Obj.repr f in Obj.repr f

type reflect =
| ReflectT
| ReflectF

(** val negb : bool -> bool **)

let negb = function
| true -> false
| false -> true

type 'a option =
| Some of 'a
| None

type ('a, 'b) prod =
| Pair of 'a * 'b

(** val fst : ('a1, 'a2) prod -> 'a1 **)

let fst = function
| Pair (x, _) -> x

(** val snd : ('a1, 'a2) prod -> 'a2 **)

let snd = function
| Pair (_, y) -> y

type 'a sig0 = 'a
  (* singleton inductive, whose constructor was exist *)



(** val pred : Z.t -> Z.t **)

let pred = Z.pred

(** val add : Z.t -> Z.t -> Z.t **)

let rec add = Z.add

(** val mul : Z.t -> Z.t -> Z.t **)

let rec mul = Z.mul

(** val sub : Z.t -> Z.t -> Z.t **)

let rec sub = fun x y -> Z.max (Z.sub x y) Z.zero

type 't reverseCoercionSource = 't

type 't reverseCoercionTarget = 't

(** val reverse_coercion :
    'a1 -> 'a2 reverseCoercionSource -> 'a1 reverseCoercionTarget **)

let reverse_coercion x' _ =
  x'

module Option =
 struct
  (** val apply : ('a1 -> 'a2) -> 'a2 -> 'a1 option -> 'a2 **)

  let apply f x = function
  | Some y -> f y
  | None -> x

  (** val bind : ('a1 -> 'a2 option) -> 'a1 option -> 'a2 option **)

  let bind f =
    apply f None
 end

type ('aT, 'rT) simpl_fun =
  'aT -> 'rT
  (* singleton inductive, whose constructor was SimplFun *)

(** val fun_of_simpl : ('a1, 'a2) simpl_fun -> 'a1 -> 'a2 **)

let fun_of_simpl f =
  f

(** val comp : ('a2 -> 'a1) -> ('a3 -> 'a2) -> 'a3 -> 'a1 **)

let comp f g x =
  f (g x)

(** val pcomp :
    ('a2 -> 'a1 option) -> ('a3 -> 'a2 option) -> 'a3 -> 'a1 option **)

let pcomp f g x =
  Option.bind f (g x)

(** val iffP : bool -> reflect -> reflect **)

let iffP _ pb =
  let _evar_0_ = fun _ _ _ -> ReflectT in
  let _evar_0_0 = fun _ _ _ -> ReflectF in
  (match pb with
   | ReflectT -> _evar_0_ __ __ __
   | ReflectF -> _evar_0_0 __ __ __)

(** val altP : bool -> reflect -> bool **)

let altP _ pb =
  let _evar_0_ = fun _ _ -> true in
  let _evar_0_0 = fun _ _ -> false in
  (match pb with
   | ReflectT -> _evar_0_ __ __
   | ReflectF -> _evar_0_0 __ __)

(** val idP : bool -> reflect **)

let idP = function
| true -> ReflectT
| false -> ReflectF

(** val andP : bool -> bool -> reflect **)

let andP b1 b2 =
  if b1 then if b2 then ReflectT else ReflectF else ReflectF

type 't pred0 = 't -> bool

type 't simpl_pred = ('t, bool) simpl_fun

(** val simplPred : 'a1 pred0 -> 'a1 simpl_pred **)

let simplPred p =
  p

module PredOfSimpl =
 struct
  (** val coerce : 'a1 simpl_pred -> 'a1 pred0 **)

  let coerce =
    fun_of_simpl
 end

type 't rel = 't -> 't pred0

type 't eq_axiom = 't -> 't -> reflect

module Coq_hasDecEq =
 struct
  type 't axioms_ = { eq_op : 't rel; eqP : 't eq_axiom }

  (** val eq_op : 'a1 axioms_ -> 'a1 rel **)

  let eq_op record =
    record.eq_op

  (** val eqP : 'a1 axioms_ -> 'a1 eq_axiom **)

  let eqP record =
    record.eqP
 end

module Equality =
 struct
  type 't axioms_ =
    't Coq_hasDecEq.axioms_
    (* singleton inductive, whose constructor was Class *)

  (** val eqtype_hasDecEq_mixin : 'a1 axioms_ -> 'a1 Coq_hasDecEq.axioms_ **)

  let eqtype_hasDecEq_mixin record =
    record

  type coq_type =
    __ axioms_
    (* singleton inductive, whose constructor was Pack *)

  type sort = __

  (** val coq_class : coq_type -> sort axioms_ **)

  let coq_class record =
    record
 end

(** val eq_op0 : Equality.coq_type -> Equality.sort rel **)

let eq_op0 s =
  s.Coq_hasDecEq.eq_op

(** val eqP0 : Equality.coq_type -> Equality.sort eq_axiom **)

let eqP0 s =
  s.Coq_hasDecEq.eqP

type eq_xor_neq =
| EqNotNeq
| NeqNotEq

(** val eqVneq :
    Equality.coq_type -> Equality.sort -> Equality.sort -> eq_xor_neq **)

let eqVneq t x y =
  let _evar_0_ = fun _ -> EqNotNeq in
  let _evar_0_0 = fun _ -> NeqNotEq in
  if altP (eq_op0 t x y) (eqP0 t x y) then _evar_0_ __ else _evar_0_0 __

(** val eqb : bool -> bool -> bool **)

let eqb = ( = )

(** val eqbP : bool eq_axiom **)

let eqbP __top_assumption_ =
  let _evar_0_ = fun __top_assumption_0 ->
    let _evar_0_ = ReflectT in
    let _evar_0_0 = ReflectF in
    if __top_assumption_0 then _evar_0_ else _evar_0_0
  in
  let _evar_0_0 = fun __top_assumption_0 ->
    let _evar_0_0 = ReflectF in
    let _evar_0_1 = ReflectT in
    if __top_assumption_0 then _evar_0_0 else _evar_0_1
  in
  if __top_assumption_ then _evar_0_ else _evar_0_0

(** val hB_unnamed_factory_3 : bool Coq_hasDecEq.axioms_ **)

let hB_unnamed_factory_3 =
  { Coq_hasDecEq.eq_op = eqb; Coq_hasDecEq.eqP = eqbP }

(** val datatypes_bool__canonical__eqtype_Equality : Equality.coq_type **)

let datatypes_bool__canonical__eqtype_Equality =
  Obj.magic hB_unnamed_factory_3

module Coq_isSub =
 struct
  type ('t, 'sub_sort) axioms_ = { val_subdef : ('sub_sort -> 't);
                                   coq_Sub : ('t -> __ -> 'sub_sort);
                                   coq_Sub_rect : (__ -> ('t -> __ -> __) ->
                                                  'sub_sort -> __) }

  (** val val_subdef : 'a1 pred0 -> ('a1, 'a2) axioms_ -> 'a2 -> 'a1 **)

  let val_subdef _ record =
    record.val_subdef

  (** val coq_Sub : 'a1 pred0 -> ('a1, 'a2) axioms_ -> 'a1 -> 'a2 **)

  let coq_Sub _ record x =
    record.coq_Sub x __
 end

module SubType =
 struct
  type ('t, 's) axioms_ =
    ('t, 's) Coq_isSub.axioms_
    (* singleton inductive, whose constructor was Class *)

  (** val eqtype_isSub_mixin :
      'a1 pred0 -> ('a1, 'a2) axioms_ -> ('a1, 'a2) Coq_isSub.axioms_ **)

  let eqtype_isSub_mixin _ record =
    record

  type 't coq_type =
    ('t, __) axioms_
    (* singleton inductive, whose constructor was Pack *)

  type 't sort = __

  (** val coq_class : 'a1 pred0 -> 'a1 coq_type -> ('a1, 'a1 sort) axioms_ **)

  let coq_class _ record =
    record

  (** val phant_on_ : 'a1 pred0 -> 'a1 coq_type -> ('a1, 'a1 sort) axioms_ **)

  let phant_on_ _ s =
    s
 end

(** val sub0 :
    'a1 pred0 -> 'a1 SubType.coq_type -> 'a1 -> 'a1 SubType.sort **)

let sub0 =
  Coq_isSub.coq_Sub

(** val insub :
    'a1 pred0 -> 'a1 SubType.coq_type -> 'a1 -> 'a1 SubType.sort option **)

let insub p sT x =
  match idP (p x) with
  | ReflectT -> Some (sub0 p sT x)
  | ReflectF -> None

type ('t, 'x) inj_type = 't

type ('t, 'x) pcan_type = 't

(** val inj_eqAxiom :
    Equality.coq_type -> ('a1 -> Equality.sort) -> 'a1 eq_axiom **)

let inj_eqAxiom eT f x y =
  iffP (eq_op0 eT (f x) (f y)) (eqP0 eT (f x) (f y))

(** val hB_unnamed_factory_9 :
    Equality.coq_type -> ('a1 -> Equality.sort) -> ('a1, Equality.sort)
    inj_type Coq_hasDecEq.axioms_ **)

let hB_unnamed_factory_9 eT f =
  { Coq_hasDecEq.eq_op = (fun x y -> eq_op0 eT (f x) (f y));
    Coq_hasDecEq.eqP = (inj_eqAxiom eT f) }

(** val eqtype_inj_type__canonical__eqtype_Equality :
    Equality.coq_type -> ('a1 -> Equality.sort) -> Equality.coq_type **)

let eqtype_inj_type__canonical__eqtype_Equality eT f =
  hB_unnamed_factory_9 eT (Obj.magic f)

(** val hB_unnamed_factory_12 :
    Equality.coq_type -> ('a1 -> Equality.sort) -> (Equality.sort -> 'a1
    option) -> ('a1, Equality.sort) pcan_type Equality.axioms_ **)

let hB_unnamed_factory_12 eT f _ =
  Obj.magic eqtype_inj_type__canonical__eqtype_Equality eT f

(** val hB_unnamed_mixin_14 :
    Equality.coq_type -> ('a1 -> Equality.sort) -> (Equality.sort -> 'a1
    option) -> ('a1, Equality.sort) pcan_type Coq_hasDecEq.axioms_ **)

let hB_unnamed_mixin_14 =
  hB_unnamed_factory_12

(** val eqtype_pcan_type__canonical__eqtype_Equality :
    Equality.coq_type -> ('a1 -> Equality.sort) -> (Equality.sort -> 'a1
    option) -> Equality.coq_type **)

let eqtype_pcan_type__canonical__eqtype_Equality eT f g =
  hB_unnamed_mixin_14 eT (Obj.magic f) (Obj.magic g)

(** val pair_eq :
    Equality.coq_type -> Equality.coq_type -> (Equality.sort, Equality.sort)
    prod rel **)

let pair_eq t1 t2 u v =
  if eq_op0 t1 (fst u) (fst v) then eq_op0 t2 (snd u) (snd v) else false

(** val pair_eqP :
    Equality.coq_type -> Equality.coq_type -> (Equality.sort, Equality.sort)
    prod eq_axiom **)

let pair_eqP t1 t2 __top_assumption_ =
  let _evar_0_ = fun x1 x2 __top_assumption_0 ->
    let _evar_0_ = fun y1 y2 ->
      iffP
        (if eq_op0 t1 (fst (Pair (x1, x2))) (fst (Pair (y1, y2)))
         then eq_op0 t2 (snd (Pair (x1, x2))) (snd (Pair (y1, y2)))
         else false)
        (andP (eq_op0 t1 (fst (Pair (x1, x2))) (fst (Pair (y1, y2))))
          (eq_op0 t2 (snd (Pair (x1, x2))) (snd (Pair (y1, y2)))))
    in
    let Pair (a, b) = __top_assumption_0 in _evar_0_ a b
  in
  let Pair (a, b) = __top_assumption_ in _evar_0_ a b

(** val hB_unnamed_factory_38 :
    Equality.coq_type -> Equality.coq_type -> (Equality.sort, Equality.sort)
    prod Coq_hasDecEq.axioms_ **)

let hB_unnamed_factory_38 t1 t2 =
  { Coq_hasDecEq.eq_op = (pair_eq t1 t2); Coq_hasDecEq.eqP =
    (pair_eqP t1 t2) }

(** val datatypes_prod__canonical__eqtype_Equality :
    Equality.coq_type -> Equality.coq_type -> Equality.coq_type **)

let datatypes_prod__canonical__eqtype_Equality t1 t2 =
  Obj.magic hB_unnamed_factory_38 t1 t2

(** val eqn : Z.t -> Z.t -> bool **)

let rec eqn = ( = )

(** val eqnP : Z.t eq_axiom **)

let eqnP n m0 =
  iffP (eqn n m0) (idP (eqn n m0))

(** val hB_unnamed_factory_1 : Z.t Coq_hasDecEq.axioms_ **)

let hB_unnamed_factory_1 =
  { Coq_hasDecEq.eq_op = eqn; Coq_hasDecEq.eqP = eqnP }

(** val datatypes_nat__canonical__eqtype_Equality : Equality.coq_type **)

let datatypes_nat__canonical__eqtype_Equality =
  Obj.magic hB_unnamed_factory_1

(** val addn : Z.t -> Z.t -> Z.t **)

let addn =
  add

(** val subn : Z.t -> Z.t -> Z.t **)

let subn =
  sub

(** val leq : Z.t -> Z.t -> bool **)

let leq m0 n =
  eq_op0 datatypes_nat__canonical__eqtype_Equality (Obj.magic subn m0 n)
    (Obj.magic Z.zero)

(** val muln : Z.t -> Z.t -> Z.t **)

let muln =
  mul

(** val expn : Z.t -> Z.t -> Z.t **)

let expn = fun x y -> Z.pow x (Z.to_int y)

(** val double : Z.t -> Z.t **)

let rec double = fun x -> Z.add x x

(** val divn : Z.t -> Z.t -> Z.t **)

let divn = Z.ediv

(** val modn : Z.t -> Z.t -> Z.t **)

let modn = Z.erem

(** val dvdn : Z.t -> Z.t -> bool **)

let dvdn d m0 =
  eq_op0 datatypes_nat__canonical__eqtype_Equality (Obj.magic modn m0 d)
    (Obj.magic Z.zero)

module Coq_hasChoice =
 struct
  type 't axioms_ =
    't pred0 -> Z.t -> 't option
    (* singleton inductive, whose constructor was Axioms_ *)

  (** val find_subdef : 'a1 axioms_ -> 'a1 pred0 -> Z.t -> 'a1 option **)

  let find_subdef record =
    record

  type 't phant_axioms = 't axioms_
 end

module Choice =
 struct
  type 't axioms_ = { choice_hasChoice_mixin : 't Coq_hasChoice.axioms_;
                      eqtype_hasDecEq_mixin : 't Coq_hasDecEq.axioms_ }

  (** val choice_hasChoice_mixin :
      'a1 axioms_ -> 'a1 Coq_hasChoice.axioms_ **)

  let choice_hasChoice_mixin record =
    record.choice_hasChoice_mixin

  type coq_type =
    __ axioms_
    (* singleton inductive, whose constructor was Pack *)

  type sort = __

  (** val coq_class : coq_type -> sort axioms_ **)

  let coq_class record =
    record
 end

(** val find_subdef0 :
    Choice.coq_type -> Choice.sort pred0 -> Z.t -> Choice.sort option **)

let find_subdef0 s x x0 =
  s.Choice.choice_hasChoice_mixin x x0

(** val pCanHasChoice :
    Choice.coq_type -> ('a1 -> Choice.sort) -> (Choice.sort -> 'a1 option) ->
    'a1 Coq_hasChoice.phant_axioms **)

let pCanHasChoice t _ f' =
  let liftP = fun sP -> simplPred (fun x -> Option.apply sP false (f' x)) in
  let sf = fun sP n ->
    Option.bind f' (find_subdef0 t (PredOfSimpl.coerce (liftP sP)) n)
  in
  (fun sP -> fun_of_simpl (sf sP))

(** val nat_hasChoice : Z.t Coq_hasChoice.phant_axioms **)

let nat_hasChoice =
  let f = fun p n -> if p n then Some n else None in
  (fun p -> fun_of_simpl (f p))

(** val hB_unnamed_factory_20 : Z.t Coq_hasChoice.phant_axioms **)

let hB_unnamed_factory_20 =
  nat_hasChoice

module Choice_isCountable =
 struct
  type 't axioms_ = { pickle : ('t -> Z.t); unpickle : (Z.t -> 't option) }

  (** val pickle : 'a1 axioms_ -> 'a1 -> Z.t **)

  let pickle record =
    record.pickle

  (** val unpickle : 'a1 axioms_ -> Z.t -> 'a1 option **)

  let unpickle record =
    record.unpickle
 end

module Countable =
 struct
  type 't axioms_ = { choice_hasChoice_mixin : 't Coq_hasChoice.axioms_;
                      eqtype_hasDecEq_mixin : 't Coq_hasDecEq.axioms_;
                      choice_Choice_isCountable_mixin : 't
                                                        Choice_isCountable.axioms_ }

  (** val eqtype_hasDecEq_mixin : 'a1 axioms_ -> 'a1 Coq_hasDecEq.axioms_ **)

  let eqtype_hasDecEq_mixin record =
    record.eqtype_hasDecEq_mixin

  (** val choice_Choice_isCountable_mixin :
      'a1 axioms_ -> 'a1 Choice_isCountable.axioms_ **)

  let choice_Choice_isCountable_mixin record =
    record.choice_Choice_isCountable_mixin

  type coq_type =
    __ axioms_
    (* singleton inductive, whose constructor was Pack *)

  type sort = __

  (** val coq_class : coq_type -> sort axioms_ **)

  let coq_class record =
    record

  module Exports =
   struct
    (** val choice_Countable_class__to__eqtype_Equality_class :
        'a1 axioms_ -> 'a1 Equality.axioms_ **)

    let choice_Countable_class__to__eqtype_Equality_class c =
      c.eqtype_hasDecEq_mixin

    (** val choice_Countable__to__eqtype_Equality :
        coq_type -> Equality.coq_type **)

    let choice_Countable__to__eqtype_Equality =
      choice_Countable_class__to__eqtype_Equality_class

    (** val choice_Countable_class__to__choice_Choice_class :
        'a1 axioms_ -> 'a1 Choice.axioms_ **)

    let choice_Countable_class__to__choice_Choice_class c =
      { Choice.choice_hasChoice_mixin = c.choice_hasChoice_mixin;
        Choice.eqtype_hasDecEq_mixin = c.eqtype_hasDecEq_mixin }

    (** val choice_Countable__to__choice_Choice :
        coq_type -> Choice.coq_type **)

    let choice_Countable__to__choice_Choice =
      choice_Countable_class__to__choice_Choice_class
   end
 end

(** val pickle0 : Countable.coq_type -> Countable.sort -> Z.t **)

let pickle0 s x =
  s.Countable.choice_Choice_isCountable_mixin.Choice_isCountable.pickle x

(** val unpickle0 : Countable.coq_type -> Z.t -> Countable.sort option **)

let unpickle0 s x =
  s.Countable.choice_Choice_isCountable_mixin.Choice_isCountable.unpickle x

module Coq_isCountable =
 struct
  type 't axioms_ = { pickle : ('t -> Z.t); unpickle : (Z.t -> 't option) }

  (** val pickle : 'a1 axioms_ -> 'a1 -> Z.t **)

  let pickle record =
    record.pickle

  (** val unpickle : 'a1 axioms_ -> Z.t -> 'a1 option **)

  let unpickle record =
    record.unpickle

  (** val phant_Build : ('a1 -> Z.t) -> (Z.t -> 'a1 option) -> 'a1 axioms_ **)

  let phant_Build pickle1 unpickle1 =
    { pickle = pickle1; unpickle = unpickle1 }

  type 't phant_axioms = 't axioms_
 end

(** val pCanIsCountable :
    Countable.coq_type -> ('a1 -> Countable.sort) -> (Countable.sort -> 'a1
    option) -> 'a1 Coq_isCountable.axioms_ **)

let pCanIsCountable t f f' =
  Coq_isCountable.phant_Build (comp (pickle0 t) f) (pcomp f' (unpickle0 t))

(** val hB_unnamed_factory_87 :
    Countable.coq_type -> ('a1 -> Countable.sort) -> (Countable.sort -> 'a1
    option) -> ('a1, Countable.sort) pcan_type Coq_isCountable.phant_axioms **)

let hB_unnamed_factory_87 =
  pCanIsCountable

(** val hB_unnamed_mixin_106 :
    Countable.coq_type -> Countable.sort pred0 -> Countable.sort
    SubType.coq_type -> Choice.sort SubType.sort Coq_hasChoice.phant_axioms **)

let hB_unnamed_mixin_106 t p sT =
  pCanHasChoice (Countable.Exports.choice_Countable__to__choice_Choice t)
    (SubType.phant_on_ p sT).Coq_isSub.val_subdef (insub p sT)

(** val hB_unnamed_mixin_107 :
    Countable.coq_type -> Countable.sort pred0 -> Countable.sort
    SubType.coq_type -> (Equality.sort SubType.sort, Equality.sort) inj_type
    Coq_hasDecEq.axioms_ **)

let hB_unnamed_mixin_107 t p sT =
  { Coq_hasDecEq.eq_op = (fun x y ->
    eq_op0 (Countable.Exports.choice_Countable__to__eqtype_Equality t)
      ((SubType.phant_on_ p sT).Coq_isSub.val_subdef x)
      ((SubType.phant_on_ p sT).Coq_isSub.val_subdef y));
    Coq_hasDecEq.eqP =
    (inj_eqAxiom (Countable.Exports.choice_Countable__to__eqtype_Equality t)
      (SubType.phant_on_ p sT).Coq_isSub.val_subdef) }

(** val hB_unnamed_mixin_109 :
    Countable.coq_type -> Countable.sort pred0 -> Countable.sort
    SubType.coq_type -> (Countable.sort SubType.sort, Countable.sort)
    pcan_type Choice_isCountable.axioms_ **)

let hB_unnamed_mixin_109 t p sT =
  { Choice_isCountable.pickle =
    (hB_unnamed_factory_87 t (SubType.phant_on_ p sT).Coq_isSub.val_subdef
      (insub p sT)).Coq_isCountable.pickle;
    Choice_isCountable.unpickle =
    (hB_unnamed_factory_87 t (SubType.phant_on_ p sT).Coq_isSub.val_subdef
      (insub p sT)).Coq_isCountable.unpickle }

(** val eqtype_sub_type__canonical__choice_Countable :
    Countable.coq_type -> Countable.sort pred0 -> Countable.sort
    SubType.coq_type -> Countable.coq_type **)

let eqtype_sub_type__canonical__choice_Countable t p sT =
  { Countable.choice_hasChoice_mixin = (hB_unnamed_mixin_106 t p sT);
    Countable.eqtype_hasDecEq_mixin = (hB_unnamed_mixin_107 t p sT);
    Countable.choice_Choice_isCountable_mixin =
    (hB_unnamed_mixin_109 t p sT) }

(** val hB_unnamed_factory_120 : Z.t Choice_isCountable.axioms_ **)

let hB_unnamed_factory_120 =
  { Choice_isCountable.pickle = (fun x -> x); Choice_isCountable.unpickle =
    (fun x -> Some x) }

(** val datatypes_nat__canonical__choice_Countable : Countable.coq_type **)

let datatypes_nat__canonical__choice_Countable =
  { Countable.choice_hasChoice_mixin = (Obj.magic hB_unnamed_factory_20);
    Countable.eqtype_hasDecEq_mixin = (Obj.magic hB_unnamed_factory_1);
    Countable.choice_Choice_isCountable_mixin =
    (Obj.magic hB_unnamed_factory_120) }

type ordinal = Z.t
  (* singleton inductive, whose constructor was Ordinal *)

(** val nat_of_ord : Z.t -> ordinal -> Z.t **)

let nat_of_ord _ i =
  i

(** val hB_unnamed_factory_57 : Z.t -> (Z.t, ordinal) Coq_isSub.axioms_ **)

let hB_unnamed_factory_57 n =
  { Coq_isSub.val_subdef = (nat_of_ord n); Coq_isSub.coq_Sub = (fun x _ ->
    x); Coq_isSub.coq_Sub_rect = (fun _ k_S u -> k_S u __) }

(** val fintype_ordinal__canonical__eqtype_SubType :
    Z.t -> Z.t SubType.coq_type **)

let fintype_ordinal__canonical__eqtype_SubType n =
  Obj.magic hB_unnamed_factory_57 n

(** val hB_unnamed_factory_59 : Z.t -> ordinal Countable.axioms_ **)

let hB_unnamed_factory_59 n =
  Obj.magic eqtype_sub_type__canonical__choice_Countable
    datatypes_nat__canonical__choice_Countable (fun x ->
    leq (Z.succ (Obj.magic x)) n)
    (reverse_coercion
      (Obj.magic fintype_ordinal__canonical__eqtype_SubType n) __)

(** val hB_unnamed_mixin_63 : Z.t -> ordinal Coq_hasDecEq.axioms_ **)

let hB_unnamed_mixin_63 n =
  (hB_unnamed_factory_59 n).Countable.eqtype_hasDecEq_mixin

(** val fintype_ordinal__canonical__eqtype_Equality :
    Z.t -> Equality.coq_type **)

let fintype_ordinal__canonical__eqtype_Equality n =
  Obj.magic hB_unnamed_mixin_63 n

(** val isqrt : Z.t -> Z.t **)

let rec isqrt = Z.sqrt

(** val nsqrt : Z.t -> Z.t **)

let nsqrt =
  isqrt

(** val calc_m' : Z.t -> Z.t -> Z.t -> Z.t **)

let calc_m' n m0 k0 =
  subn (nsqrt n) (modn (addn (nsqrt n) m0) k0)

(** val calc_k' : Z.t -> Z.t -> Z.t -> Z.t **)

let calc_k' n m' k0 =
  divn (subn n (expn m' (Z.succ (Z.succ Z.zero)))) k0

(** val calc_a' : Z.t -> Z.t -> Z.t -> Z.t -> Z.t -> Z.t **)

let calc_a' n m' k0 a b =
  divn (addn (muln a m') (muln n b)) k0

(** val calc_b' : Z.t -> Z.t -> Z.t -> Z.t -> Z.t **)

let calc_b' m' k0 a b =
  divn (addn a (muln b m')) k0

type base = { m : Z.t; k : Z.t; sign : bool }

(** val start_base : Z.t -> base **)

let start_base n =
  { m = (nsqrt n); k = (Z.succ Z.zero); sign = false }

(** val validBase : Z.t -> base -> bool **)

let validBase n b =
  if if leq (Z.succ Z.zero) b.k then leq b.k (addn (nsqrt n) b.m) else false
  then if if leq (Z.succ Z.zero) b.m then leq b.m (nsqrt n) else false
       then if leq (Z.succ (nsqrt n)) (addn b.m b.k)
            then dvdn b.k (subn n (expn b.m (Z.succ (Z.succ Z.zero))))
            else false
       else false
  else false

type vbase = base
  (* singleton inductive, whose constructor was VBase *)

(** val base_of_vbase : Z.t -> vbase -> base **)

let base_of_vbase _ b =
  b

(** val hB_unnamed_factory_0 : Z.t -> (base, vbase) Coq_isSub.axioms_ **)

let hB_unnamed_factory_0 n =
  { Coq_isSub.val_subdef = (base_of_vbase n); Coq_isSub.coq_Sub = (fun x _ ->
    x); Coq_isSub.coq_Sub_rect = (fun _ k_S u -> k_S u __) }

(** val main_vbase__canonical__eqtype_SubType :
    Z.t -> base SubType.coq_type **)

let main_vbase__canonical__eqtype_SubType n =
  Obj.magic hB_unnamed_factory_0 n

(** val start_vbase : Z.t -> vbase **)

let start_vbase =
  start_base

type donor = ((ordinal, ordinal) prod, bool) prod

(** val donor2vbase : Z.t -> donor -> vbase option **)

let donor2vbase n = function
| Pair (p, sign0) ->
  let Pair (m0, k0) = p in
  Obj.magic insub (validBase n) (main_vbase__canonical__eqtype_SubType n)
    { m = (Z.succ (nat_of_ord (nsqrt n) m0)); k = (Z.succ
    (nat_of_ord (double (nsqrt n)) k0)); sign = sign0 }

(** val vbase2donor : Z.t -> vbase -> donor **)

let vbase2donor n vb =
  Pair ((Pair
    ((pred
       ((Obj.magic SubType.phant_on_ (validBase n)
          (main_vbase__canonical__eqtype_SubType n)).Coq_isSub.val_subdef
         vb).m),
    (pred
      ((Obj.magic SubType.phant_on_ (validBase n)
         (main_vbase__canonical__eqtype_SubType n)).Coq_isSub.val_subdef
        vb).k))),
    ((Obj.magic SubType.phant_on_ (validBase n)
       (main_vbase__canonical__eqtype_SubType n)).Coq_isSub.val_subdef
      vb).sign)

(** val hB_unnamed_factory_5 : Z.t -> vbase Equality.axioms_ **)

let hB_unnamed_factory_5 n =
  Obj.magic eqtype_pcan_type__canonical__eqtype_Equality
    (datatypes_prod__canonical__eqtype_Equality
      (datatypes_prod__canonical__eqtype_Equality
        (fintype_ordinal__canonical__eqtype_Equality (nsqrt n))
        (fintype_ordinal__canonical__eqtype_Equality (double (nsqrt n))))
      datatypes_bool__canonical__eqtype_Equality)
    (vbase2donor n) (donor2vbase n)

(** val hB_unnamed_mixin_7 : Z.t -> vbase Coq_hasDecEq.axioms_ **)

let hB_unnamed_mixin_7 =
  hB_unnamed_factory_5

(** val main_vbase__canonical__eqtype_Equality : Z.t -> Equality.coq_type **)

let main_vbase__canonical__eqtype_Equality n =
  Obj.magic hB_unnamed_mixin_7 n

(** val step : Z.t -> base -> base **)

let step n b =
  let m' = calc_m' n b.m b.k in
  { m = m'; k = (calc_k' n m' b.k); sign = (negb b.sign) }

(** val vstep : Z.t -> vbase -> vbase **)

let vstep n b =
  step n
    ((Obj.magic SubType.phant_on_ (validBase n)
       (main_vbase__canonical__eqtype_SubType n)).Coq_isSub.val_subdef
      b)

type terminates = Z.t

type state = { s_vbase : vbase; s_a : Z.t; s_b : Z.t;
               s_terminates : terminates }

(** val terminates_initial_state : Z.t -> terminates **)

let terminates_initial_state _ =
  Z.zero

(** val initial_state : Z.t -> state **)

let initial_state n =
  { s_vbase = (vstep n (start_vbase n)); s_a = (nsqrt n); s_b = (Z.succ
    Z.zero); s_terminates = (terminates_initial_state n) }

(** val helper4 : Z.t -> state -> terminates **)

let helper4 _ s =
  Z.succ s.s_terminates

(** val next_step : Z.t -> state -> state **)

let next_step n s =
  let vb' = vstep n s.s_vbase in
  let a' =
    calc_a' n (base_of_vbase n vb').m (base_of_vbase n s.s_vbase).k s.s_a
      s.s_b
  in
  let b' =
    calc_b' (base_of_vbase n vb').m (base_of_vbase n s.s_vbase).k s.s_a s.s_b
  in
  { s_vbase = vb'; s_a = a'; s_b = b'; s_terminates = (helper4 n s) }

(** val eqVneq' : Z.t -> state -> bool **)

let eqVneq' n s =
  match eqVneq (main_vbase__canonical__eqtype_Equality n)
          (Obj.magic s.s_vbase) (Obj.magic start_vbase n) with
  | EqNotNeq -> false
  | NeqNotEq -> true

(** val chakravala_inner : Z.t -> state -> state **)

let rec chakravala_inner n x =
  if eqVneq' n x then let y = next_step n x in chakravala_inner n y else x

(** val chakravala : Z.t -> (Z.t, Z.t) prod **)

let chakravala n =
  match eqVneq datatypes_nat__canonical__eqtype_Equality
          (Obj.magic expn (isqrt n) (Z.succ (Z.succ Z.zero))) (Obj.magic n) with
  | EqNotNeq -> Pair ((Z.succ Z.zero), Z.zero)
  | NeqNotEq ->
    let s = chakravala_inner n (initial_state n) in Pair (s.s_a, s.s_b)
